"""Generates core/.../R.java (int ids for string/plurals/array/id resources) from res/values/*.xml.
Run from the port/ directory: python tools/genR.py"""
import re, xml.etree.ElementTree as ET
RES = "core/src/main/resources/res/"
OUT = "core/src/main/java/com/brucelet/spacetrader/R.java"
DRAWABLES = "alien beetle blankicon bottle bumblebee destroyed dragonfly firefly flea gnat grasshopper hornet mantis monster moon mosquito pirate police retire scarab special termite trader wasp".split()
groups = {"string": [], "plurals": [], "array": [], "id": [], "drawable": DRAWABLES}
for f in ("strings.xml", "arrays.xml", "ids.xml"):
    for e in ET.parse(RES + f).getroot():
        n = e.get("name")
        if e.tag == "string": groups["string"].append(n)
        elif e.tag == "plurals": groups["plurals"].append(n)
        elif e.tag in ("string-array", "array", "integer-array"): groups["array"].append(n)
        elif e.tag == "item" and e.get("type") == "id": groups["id"].append(n)
seen = 0x7f000000
lines = ["package com.brucelet.spacetrader;", "", "/** GENERATED by tools/genR.py - do not edit. */", "public final class R {", "\tprivate R() {}"]
for g, names in groups.items():
    lines.append("\tpublic static final class %s {" % g)
    for n in dict.fromkeys(names):
        seen += 1
        lines.append("\t\tpublic static final int %s = 0x%08x;" % (n, seen))
    lines.append("\t}")
lines.append("}")
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print({g: len(set(v)) for g, v in groups.items()})
